### ISSUE TITLE
Create a "How to use this document"

### ISSUE THREAD

**Issue by kevwalsh** [CivicActions/agile-baseline#3]
Include: 
- Git workflow (forking/pull-request)
- TBD

**Comment by openprivacy** [comment]
Re: "git workflow" we are working to make this one general purpose:
https://git.civicactions.net/dsca/globalnet2/blob/develop/docs/workflow.md

**Comment by kevwalsh** [comment]
@openprivacy one must be a member of the Gnet team on gitlab to see that file.
